const styles = {
    accountsButton: {
        height: 50,
        borderRadius: 25,
        aspectRatio: 1,
        backgroundColor: 'white',
        opacity: 0.6,
    },
    accountsFunds: {
        backgroundColor: customStyles.colors.blackMain,
    },
    accountsTitle: {
        flex: 1,
        alignItems: 'stretch',
        justifyContent: 'flex-start',
        paddingLeft: 35,
        marginTop: 30,
        marginBottom: 30,
    },
    accountsNoFundMessage: {
        flex: 10,
        alignItems: 'center',
        justifyContent: 'flex-start',
        padding: 10,
    },
    accountsScroll: {
        flex: 10,
    },
    accountsContent: {
        flex: 11,
        alignItems: 'center',
        justifyContent: 'flex-start',
        marginBottom: 30,
    },
    accountsMainText: {
        color: customStyles.colors.white,
        fontFamily: 'Assistant',
    },
    h1Text: {
        fontSize: 27,
        fontWeight: '800',
    },
    h2Text: {
        fontSize: 20,
        marginBottom: 30,
        fontWeight: '400',
    },
    accountsHeaderContainer: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        width: windowWidth - windowWidth / 2.5,
        height: '100%',
    },
    modalContainer: {
        height: SCREEN_HEIGHT,
        width: '100%',
        backgroundColor: customStyles.colors.blackBar,
        position: 'absolute',
        top: SCREEN_HEIGHT,
        borderRadius: 25,
        padding: 15,
    },
    modalTitle: {
        justifyContent: 'center',
        textAlign: 'center',
        width: '100%',
        fontSize: 28,
        color: customStyles.colors.white,
        fontWeight: 'bold',
    },
    modalCountContainer: {
        height: '40%',
        width: '100%',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    modalButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        width: '100%',
    },
    modalCountText: {
        textAlign: 'center',
        minWidth: '40%',
        marginBottom: 25,
        fontSize: 20,
        color: customStyles.colors.white,
        borderBottomWidth: 1,
        borderBottomColor: customStyles.colors.white,
    },
    modalPopUpButtonContainer: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    modalPopUpTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
        color: customStyles.colors.white,
    },
    modalPopUpContent: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalPopUpButton: {
        fontSize: 16,
        color: customStyles.colors.white,
    },
};
